jobs:
  build_non_win_images:
    name: Build Native Image ${{ matrix.platform }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout the repository
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: graalvm/setup-graalvm@v1
      with:
        components: native-image
        github-token: ${{ secrets.GITHUB_TOKEN }}
        java-version: '17'
        version: 22.3.1
    - continue-on-error: true
      uses: actions/cache/restore@v4
      with:
        enableCrossOsArchive: true
        fail-on-cache-miss: true
        key: libs-${{ github.run_id }}
        path: 'build/libs

          build/publications

          plantuml-asl/build/libs

          plantuml-bsd/build/libs

          plantuml-epl/build/libs

          plantuml-lgpl/build/libs

          plantuml-mit/build/libs

          plantuml-gplv2/build/libs

          '
    - continue-on-error: true
      name: Generate GraalVM configuration
      run: 'mkdir native-image-config-dir

        echo ''Bob->Alice: Hello'' | java -agentlib:native-image-agent=config-output-dir=native-image-config-dir
        -jar "./build/libs/plantuml-${{ inputs.release-version }}.jar" -tpng -pipe
        > out.png

        '
    - continue-on-error: true
      name: Generate native image
      run: 'native-image -H:ConfigurationFileDirectories=native-image-config-dir --no-fallback
        --report-unsupported-elements-at-runtime -jar "build/libs/plantuml-${{ inputs.release-version
        }}.jar" -H:Path="build/libs" -H:Name="plantuml-${{ matrix.platform }}-${{
        inputs.release-version }}"

        '
    - continue-on-error: true
      name: Cache native image
      uses: actions/cache/save@v4
      with:
        enableCrossOsArchive: true
        key: native-image-${{ matrix.platform }}-${{ github.run_id }}
        path: build/libs/plantuml-${{ matrix.platform }}-*
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux-amd64
        - os: macos-latest
          platform: darwin-amd64
        - os: windows-latest
          platform: win-amd64
        os:
        - macos-latest
        - windows-latest
        - ubuntu-latest
name: Native Image
on:
  repository_dispatch:
    types: trigger-ga___native-image.yml
