jobs:
  testing-workflow-config:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      id: config
      name: configure workflow
      uses: ./.github/actions/configure-workflow
      with:
        milliseconds: 3000
name: Testing workflow config action
on:
  repository_dispatch:
    types: trigger-ga___testing-workflow-config.yml
